services:
  front-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: front-workspace
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true